import type { Metadata } from "next";
import "./globals.css";
import PrelineScript from "./components/PrelineScript";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Coverlly - Housse de protection pc portable",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={`antialiased`}
      >
       <div className="bg-black text-white sm:p-2 p-3 flex justify-center items-center overflow-hidden">
          <ul className="text-wrapper ">
            <li className="text-item ">
              🚚 Des retards sont à prévoir dans certains pays d&apos;Europe en raison des périodes de fêtes
            </li>
            <li className="text-item">
              🏷️ Obtenez -10% avec le code: HOHO24 | à utiliser lors de votre passage en caisse
            </li>
          </ul>
        </div>

        <Navbar/>
        {children}
        <Footer/>
      </body>
      <PrelineScript />
    </html>
  );
}
